## PyTorch

PyTorch is a python based scientific computing package for powerful computation on GPUs and a deep learning platform for maximum flexibility and speed.

### Tensors
Tensors are like numpy ndarray, with an additional ability that tensors can also be used on GPU to accelerate computing.

In [1]:
import torch

In [20]:
# construct 5x3 matrix, Uninitialised
x = torch.Tensor(5,3)
print(x)


 -0.0000   0.0000  -0.0000
  0.0000   0.0000   0.0000
-13.8084   0.0000   0.0000
  0.0000   0.0000   0.0000
  0.0000   0.0000   0.0000
[torch.FloatTensor of size 5x3]



In [21]:
# constuct 5x3 matrix, randomly initialized
x = torch.rand(5,3)
print(x)


 0.9060  0.5369  0.0952
 0.7685  0.1768  0.8071
 0.0370  0.4211  0.7388
 0.8362  0.5938  0.6465
 0.4591  0.9761  0.5709
[torch.FloatTensor of size 5x3]



In [22]:
print(x.size())

torch.Size([5, 3])


In [23]:
x.size()

torch.Size([5, 3])

### Addition with multiple syntax

In [24]:
y = torch.rand(5,3)
y


 0.6188  0.8048  0.7048
 0.8057  0.5045  0.9107
 0.5235  0.1820  0.6639
 0.6527  0.2342  0.3592
 0.3334  0.4862  0.7678
[torch.FloatTensor of size 5x3]

In [25]:
x+y


 1.5248  1.3417  0.8000
 1.5742  0.6813  1.7177
 0.5605  0.6031  1.4027
 1.4889  0.8281  1.0058
 0.7926  1.4624  1.3387
[torch.FloatTensor of size 5x3]

In [26]:
torch.add(x,y)


 1.5248  1.3417  0.8000
 1.5742  0.6813  1.7177
 0.5605  0.6031  1.4027
 1.4889  0.8281  1.0058
 0.7926  1.4624  1.3387
[torch.FloatTensor of size 5x3]

In [27]:
result = torch.Tensor(5,3)
torch.add(x,y,out=result)
result


 1.5248  1.3417  0.8000
 1.5742  0.6813  1.7177
 0.5605  0.6031  1.4027
 1.4889  0.8281  1.0058
 0.7926  1.4624  1.3387
[torch.FloatTensor of size 5x3]

In [28]:
x.add(y) # returns addition tensor


 1.5248  1.3417  0.8000
 1.5742  0.6813  1.7177
 0.5605  0.6031  1.4027
 1.4889  0.8281  1.0058
 0.7926  1.4624  1.3387
[torch.FloatTensor of size 5x3]

In [29]:
x.add_(y) # inplace addition


 1.5248  1.3417  0.8000
 1.5742  0.6813  1.7177
 0.5605  0.6031  1.4027
 1.4889  0.8281  1.0058
 0.7926  1.4624  1.3387
[torch.FloatTensor of size 5x3]

In [30]:
x


 1.5248  1.3417  0.8000
 1.5742  0.6813  1.7177
 0.5605  0.6031  1.4027
 1.4889  0.8281  1.0058
 0.7926  1.4624  1.3387
[torch.FloatTensor of size 5x3]

Any operation that mutates a tensor in-place is post-fixed with an `_`.    
eg. `x.add_(y), x.copy_(y) x.t_(y)`

### Indexing
We can use standard numpy like indexing

In [31]:
# get all rows of second column
x[:,1]


 1.3417
 0.6813
 0.6031
 0.8281
 1.4624
[torch.FloatTensor of size 5]

To resize/reshape the tensor use `torch.view()`

In [36]:
x = torch.rand(4,4)
y = x.view(16) # return new tensor with same data in different size
z = x.view(-1, 8) # the size at -1 will be inferred from other dimension

print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### Torch tensor <-> numpy array

#### Converting torch Tensor to  numpy array
Torch tensor and numpy array share the underlying memory location. Changing one will change the other

In [42]:
a = torch.ones(5)
a


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]

In [43]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [44]:
a.add_(1)

b

array([2., 2., 2., 2., 2.], dtype=float32)

Changing the numpy array will not change the orginal tensor.

In [45]:
b = b +1

a


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

In [46]:
b

array([3., 3., 3., 3., 3.], dtype=float32)

#### Converting numpy array to torch Tensor

In [47]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

[1. 1. 1. 1. 1.] 
 1
 1
 1
 1
 1
[torch.DoubleTensor of size 5]



In [48]:
a = a + 1
a

array([2., 2., 2., 2., 2.])

In [49]:
b


 1
 1
 1
 1
 1
[torch.DoubleTensor of size 5]

In [50]:
np.add(a, 1, out=a)

array([3., 3., 3., 3., 3.])

In [51]:
b


 1
 1
 1
 1
 1
[torch.DoubleTensor of size 5]

This [tutorial](http://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)  claims that changing the numpy array will change the torch tensor automatically. But my observation is not same.

### CUDA Tensors

Tensors can be moved onto GPU by `.cuda` method.

In [52]:
# run this cell if GPU is avaialble
if torch.cuda.is_available():
    x = x.cuda() # return a copy of x in CUDA memory
    y = y.cuda()
    x + y